[build]
  command = "npm install"
  functions = "netlify/functions"

[functions]
  included_files = ["shared/**"]
  node_bundler = "zisi"

[functions."*"]
  node_version = 18

[functions."admin-handler"]
  timeout = 60

[functions."send-reminders"]
  # Run the send-reminders function once a day at midnight UTC
  schedule = "0 0 * * *"
