-- Миграция для создания таблицы для хранения результатов диалогового тренажера
-- Дата: 2025-09-04

CREATE TABLE IF NOT EXISTS public.dialogue_simulations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    persona TEXT NOT NULL,
    dialogue_history JSONB NOT NULL,
    evaluation TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE public.dialogue_simulations IS 'Хранит результаты прохождения диалогового тренажера пользователями.';
COMMENT ON COLUMN public.dialogue_simulations.user_id IS 'Ссылка на пользователя, который проходил тренажер.';
COMMENT ON COLUMN public.dialogue_simulations.persona IS 'Тип клиента, с которым велся диалог (например, "cold", "interested").';
COMMENT ON COLUMN public.dialogue_simulations.dialogue_history IS 'Полная история диалога в формате JSON.';
COMMENT ON COLUMN public.dialogue_simulations.evaluation IS 'Текстовая оценка диалога, предоставленная ИИ.';
COMMENT ON COLUMN public.dialogue_simulations.created_at IS 'Время сохранения записи.';
